### PR TITLE
ci(tools): #449 Check for svelte errors in linting

### PR DESCRIPTION
**Pull request by MrGreenTea**
Closes: #449

### CODE REVIEW

**Comment by MrGreenTea** [comment]
Has to be tested first (the problem matchers for `eslint` and `svelte-check`)

**Comment by MrGreenTea** [comment]
`svelte-check` problem matcher works:
image

**Comment by MrGreenTea** [comment]
I think an astro matcher would be good too...

**Comment by MrGreenTea** [comment]
I have tested both `svelte-check` and `astro check` matchers and they work :+1:

**Review by Han2-Ro — APPROVED** [review]
lgtm

**Review by Han2-Ro — APPROVED** [review]

**Pull request merged**
